// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: user_service.proto

package getwayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetwayService_GetAuth_FullMethodName = "/getway.v1.GetwayService/GetAuth"
)

// GetwayServiceClient is the client API for GetwayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetwayServiceClient interface {
	GetAuth(ctx context.Context, in *GetAuthRequest, opts ...grpc.CallOption) (*GetAuthResponse, error)
}

type getwayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetwayServiceClient(cc grpc.ClientConnInterface) GetwayServiceClient {
	return &getwayServiceClient{cc}
}

func (c *getwayServiceClient) GetAuth(ctx context.Context, in *GetAuthRequest, opts ...grpc.CallOption) (*GetAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthResponse)
	err := c.cc.Invoke(ctx, GetwayService_GetAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetwayServiceServer is the server API for GetwayService service.
// All implementations must embed UnimplementedGetwayServiceServer
// for forward compatibility.
type GetwayServiceServer interface {
	GetAuth(context.Context, *GetAuthRequest) (*GetAuthResponse, error)
	mustEmbedUnimplementedGetwayServiceServer()
}

// UnimplementedGetwayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetwayServiceServer struct{}

func (UnimplementedGetwayServiceServer) GetAuth(context.Context, *GetAuthRequest) (*GetAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuth not implemented")
}
func (UnimplementedGetwayServiceServer) mustEmbedUnimplementedGetwayServiceServer() {}
func (UnimplementedGetwayServiceServer) testEmbeddedByValue()                       {}

// UnsafeGetwayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetwayServiceServer will
// result in compilation errors.
type UnsafeGetwayServiceServer interface {
	mustEmbedUnimplementedGetwayServiceServer()
}

func RegisterGetwayServiceServer(s grpc.ServiceRegistrar, srv GetwayServiceServer) {
	// If the following call panics, it indicates UnimplementedGetwayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetwayService_ServiceDesc, srv)
}

func _GetwayService_GetAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetwayServiceServer).GetAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetwayService_GetAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetwayServiceServer).GetAuth(ctx, req.(*GetAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetwayService_ServiceDesc is the grpc.ServiceDesc for GetwayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetwayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getway.v1.GetwayService",
	HandlerType: (*GetwayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuth",
			Handler:    _GetwayService_GetAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service.proto",
}
