// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: delivery_service.proto

package deliveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId             uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DeliveryNo          string                 `protobuf:"bytes,3,opt,name=delivery_no,json=deliveryNo,proto3" json:"delivery_no,omitempty"`
	Status              int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	GoodsInfo           string                 `protobuf:"bytes,5,opt,name=goods_info,json=goodsInfo,proto3" json:"goods_info,omitempty"`
	RiderId             uint64                 `protobuf:"varint,6,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RiderName           string                 `protobuf:"bytes,7,opt,name=rider_name,json=riderName,proto3" json:"rider_name,omitempty"`
	RiderPhone          string                 `protobuf:"bytes,8,opt,name=rider_phone,json=riderPhone,proto3" json:"rider_phone,omitempty"`
	PickupAddress       string                 `protobuf:"bytes,9,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress     string                 `protobuf:"bytes,10,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DispatchTime        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=dispatch_time,json=dispatchTime,proto3" json:"dispatch_time,omitempty"`
	PickupTime          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	ExpectedArrivalTime *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expected_arrival_time,json=expectedArrivalTime,proto3" json:"expected_arrival_time,omitempty"`
	DeliveredTime       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=delivered_time,json=deliveredTime,proto3" json:"delivered_time,omitempty"`
	Remark              string                 `protobuf:"bytes,15,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime          *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime          *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeliveryDetail) Reset() {
	*x = DeliveryDetail{}
	mi := &file_delivery_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryDetail) ProtoMessage() {}

func (x *DeliveryDetail) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryDetail.ProtoReflect.Descriptor instead.
func (*DeliveryDetail) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeliveryDetail) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DeliveryDetail) GetDeliveryNo() string {
	if x != nil {
		return x.DeliveryNo
	}
	return ""
}

func (x *DeliveryDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeliveryDetail) GetGoodsInfo() string {
	if x != nil {
		return x.GoodsInfo
	}
	return ""
}

func (x *DeliveryDetail) GetRiderId() uint64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *DeliveryDetail) GetRiderName() string {
	if x != nil {
		return x.RiderName
	}
	return ""
}

func (x *DeliveryDetail) GetRiderPhone() string {
	if x != nil {
		return x.RiderPhone
	}
	return ""
}

func (x *DeliveryDetail) GetPickupAddress() string {
	if x != nil {
		return x.PickupAddress
	}
	return ""
}

func (x *DeliveryDetail) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *DeliveryDetail) GetDispatchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DispatchTime
	}
	return nil
}

func (x *DeliveryDetail) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *DeliveryDetail) GetExpectedArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpectedArrivalTime
	}
	return nil
}

func (x *DeliveryDetail) GetDeliveredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredTime
	}
	return nil
}

func (x *DeliveryDetail) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *DeliveryDetail) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DeliveryDetail) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GetDeliveryByOrderIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryByOrderIdRequest) Reset() {
	*x = GetDeliveryByOrderIdRequest{}
	mi := &file_delivery_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryByOrderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryByOrderIdRequest) ProtoMessage() {}

func (x *GetDeliveryByOrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryByOrderIdRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryByOrderIdRequest) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeliveryByOrderIdRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetDeliveryByOrderIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryDetail        `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryByOrderIdResponse) Reset() {
	*x = GetDeliveryByOrderIdResponse{}
	mi := &file_delivery_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryByOrderIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryByOrderIdResponse) ProtoMessage() {}

func (x *GetDeliveryByOrderIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryByOrderIdResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryByOrderIdResponse) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeliveryByOrderIdResponse) GetDelivery() *DeliveryDetail {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type ListDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        *int32                 `protobuf:"varint,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesRequest) Reset() {
	*x = ListDeliveriesRequest{}
	mi := &file_delivery_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesRequest) ProtoMessage() {}

func (x *ListDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListDeliveriesRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ListDeliveriesRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type ListDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DeliveryDetail      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesResponse) Reset() {
	*x = ListDeliveriesResponse{}
	mi := &file_delivery_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveriesResponse) ProtoMessage() {}

func (x *ListDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveriesResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeliveriesResponse) GetItems() []*DeliveryDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateDeliveryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderId             uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DeliveryNo          string                 `protobuf:"bytes,2,opt,name=delivery_no,json=deliveryNo,proto3" json:"delivery_no,omitempty"`
	Status              int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	GoodsInfo           string                 `protobuf:"bytes,4,opt,name=goods_info,json=goodsInfo,proto3" json:"goods_info,omitempty"`
	RiderId             uint64                 `protobuf:"varint,5,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RiderName           string                 `protobuf:"bytes,6,opt,name=rider_name,json=riderName,proto3" json:"rider_name,omitempty"`
	RiderPhone          string                 `protobuf:"bytes,7,opt,name=rider_phone,json=riderPhone,proto3" json:"rider_phone,omitempty"`
	PickupAddress       string                 `protobuf:"bytes,8,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	DeliveryAddress     string                 `protobuf:"bytes,9,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	ExpectedArrivalTime string                 `protobuf:"bytes,10,opt,name=expected_arrival_time,json=expectedArrivalTime,proto3" json:"expected_arrival_time,omitempty"`
	Remark              string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateDeliveryRequest) Reset() {
	*x = CreateDeliveryRequest{}
	mi := &file_delivery_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryRequest) ProtoMessage() {}

func (x *CreateDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryRequest.ProtoReflect.Descriptor instead.
func (*CreateDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDeliveryRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateDeliveryRequest) GetDeliveryNo() string {
	if x != nil {
		return x.DeliveryNo
	}
	return ""
}

func (x *CreateDeliveryRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateDeliveryRequest) GetGoodsInfo() string {
	if x != nil {
		return x.GoodsInfo
	}
	return ""
}

func (x *CreateDeliveryRequest) GetRiderId() uint64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *CreateDeliveryRequest) GetRiderName() string {
	if x != nil {
		return x.RiderName
	}
	return ""
}

func (x *CreateDeliveryRequest) GetRiderPhone() string {
	if x != nil {
		return x.RiderPhone
	}
	return ""
}

func (x *CreateDeliveryRequest) GetPickupAddress() string {
	if x != nil {
		return x.PickupAddress
	}
	return ""
}

func (x *CreateDeliveryRequest) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *CreateDeliveryRequest) GetExpectedArrivalTime() string {
	if x != nil {
		return x.ExpectedArrivalTime
	}
	return ""
}

func (x *CreateDeliveryRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryDetail        `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeliveryResponse) Reset() {
	*x = CreateDeliveryResponse{}
	mi := &file_delivery_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryResponse) ProtoMessage() {}

func (x *CreateDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryResponse.ProtoReflect.Descriptor instead.
func (*CreateDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDeliveryResponse) GetDelivery() *DeliveryDetail {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type UpdateDeliveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	RiderId       uint64                 `protobuf:"varint,4,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RiderName     string                 `protobuf:"bytes,5,opt,name=rider_name,json=riderName,proto3" json:"rider_name,omitempty"`
	RiderPhone    string                 `protobuf:"bytes,6,opt,name=rider_phone,json=riderPhone,proto3" json:"rider_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusRequest) Reset() {
	*x = UpdateDeliveryStatusRequest{}
	mi := &file_delivery_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusRequest) ProtoMessage() {}

func (x *UpdateDeliveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDeliveryStatusRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateDeliveryStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateDeliveryStatusRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetRiderId() uint64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *UpdateDeliveryStatusRequest) GetRiderName() string {
	if x != nil {
		return x.RiderName
	}
	return ""
}

func (x *UpdateDeliveryStatusRequest) GetRiderPhone() string {
	if x != nil {
		return x.RiderPhone
	}
	return ""
}

type UpdateDeliveryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryDetail        `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryStatusResponse) Reset() {
	*x = UpdateDeliveryStatusResponse{}
	mi := &file_delivery_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryStatusResponse) ProtoMessage() {}

func (x *UpdateDeliveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDeliveryStatusResponse) GetDelivery() *DeliveryDetail {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type UpdateDeliveryByOrderIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	RiderId       uint64                 `protobuf:"varint,4,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RiderName     string                 `protobuf:"bytes,5,opt,name=rider_name,json=riderName,proto3" json:"rider_name,omitempty"`
	RiderPhone    string                 `protobuf:"bytes,6,opt,name=rider_phone,json=riderPhone,proto3" json:"rider_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryByOrderIdRequest) Reset() {
	*x = UpdateDeliveryByOrderIdRequest{}
	mi := &file_delivery_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryByOrderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryByOrderIdRequest) ProtoMessage() {}

func (x *UpdateDeliveryByOrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryByOrderIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryByOrderIdRequest) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDeliveryByOrderIdRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateDeliveryByOrderIdRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateDeliveryByOrderIdRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateDeliveryByOrderIdRequest) GetRiderId() uint64 {
	if x != nil {
		return x.RiderId
	}
	return 0
}

func (x *UpdateDeliveryByOrderIdRequest) GetRiderName() string {
	if x != nil {
		return x.RiderName
	}
	return ""
}

func (x *UpdateDeliveryByOrderIdRequest) GetRiderPhone() string {
	if x != nil {
		return x.RiderPhone
	}
	return ""
}

type UpdateDeliveryByOrderIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryDetail        `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryByOrderIdResponse) Reset() {
	*x = UpdateDeliveryByOrderIdResponse{}
	mi := &file_delivery_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryByOrderIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryByOrderIdResponse) ProtoMessage() {}

func (x *UpdateDeliveryByOrderIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryByOrderIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryByOrderIdResponse) Descriptor() ([]byte, []int) {
	return file_delivery_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDeliveryByOrderIdResponse) GetDelivery() *DeliveryDetail {
	if x != nil {
		return x.Delivery
	}
	return nil
}

var File_delivery_service_proto protoreflect.FileDescriptor

const file_delivery_service_proto_rawDesc = "" +
	"\n" +
	"\x16delivery_service.proto\x12\vdelivery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x05\n" +
	"\x0eDeliveryDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12\x1f\n" +
	"\vdelivery_no\x18\x03 \x01(\tR\n" +
	"deliveryNo\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"goods_info\x18\x05 \x01(\tR\tgoodsInfo\x12\x19\n" +
	"\brider_id\x18\x06 \x01(\x04R\ariderId\x12\x1d\n" +
	"\n" +
	"rider_name\x18\a \x01(\tR\triderName\x12\x1f\n" +
	"\vrider_phone\x18\b \x01(\tR\n" +
	"riderPhone\x12%\n" +
	"\x0epickup_address\x18\t \x01(\tR\rpickupAddress\x12)\n" +
	"\x10delivery_address\x18\n" +
	" \x01(\tR\x0fdeliveryAddress\x12?\n" +
	"\rdispatch_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fdispatchTime\x12;\n" +
	"\vpickup_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\x12N\n" +
	"\x15expected_arrival_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x13expectedArrivalTime\x12A\n" +
	"\x0edelivered_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\rdeliveredTime\x12\x16\n" +
	"\x06remark\x18\x0f \x01(\tR\x06remark\x12;\n" +
	"\vcreate_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"8\n" +
	"\x1bGetDeliveryByOrderIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"W\n" +
	"\x1cGetDeliveryByOrderIdResponse\x127\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1b.delivery.v1.DeliveryDetailR\bdelivery\"Z\n" +
	"\x15ListDeliveriesRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\x05H\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"K\n" +
	"\x16ListDeliveriesResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.delivery.v1.DeliveryDetailR\x05items\"\x83\x03\n" +
	"\x15CreateDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x1f\n" +
	"\vdelivery_no\x18\x02 \x01(\tR\n" +
	"deliveryNo\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"goods_info\x18\x04 \x01(\tR\tgoodsInfo\x12\x19\n" +
	"\brider_id\x18\x05 \x01(\x04R\ariderId\x12\x1d\n" +
	"\n" +
	"rider_name\x18\x06 \x01(\tR\triderName\x12\x1f\n" +
	"\vrider_phone\x18\a \x01(\tR\n" +
	"riderPhone\x12%\n" +
	"\x0epickup_address\x18\b \x01(\tR\rpickupAddress\x12)\n" +
	"\x10delivery_address\x18\t \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15expected_arrival_time\x18\n" +
	" \x01(\tR\x13expectedArrivalTime\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\"Q\n" +
	"\x16CreateDeliveryResponse\x127\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1b.delivery.v1.DeliveryDetailR\bdelivery\"\xc3\x01\n" +
	"\x1bUpdateDeliveryStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x19\n" +
	"\brider_id\x18\x04 \x01(\x04R\ariderId\x12\x1d\n" +
	"\n" +
	"rider_name\x18\x05 \x01(\tR\triderName\x12\x1f\n" +
	"\vrider_phone\x18\x06 \x01(\tR\n" +
	"riderPhone\"W\n" +
	"\x1cUpdateDeliveryStatusResponse\x127\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1b.delivery.v1.DeliveryDetailR\bdelivery\"\xc6\x01\n" +
	"\x1eUpdateDeliveryByOrderIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x19\n" +
	"\brider_id\x18\x04 \x01(\x04R\ariderId\x12\x1d\n" +
	"\n" +
	"rider_name\x18\x05 \x01(\tR\triderName\x12\x1f\n" +
	"\vrider_phone\x18\x06 \x01(\tR\n" +
	"riderPhone\"Z\n" +
	"\x1fUpdateDeliveryByOrderIdResponse\x127\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1b.delivery.v1.DeliveryDetailR\bdelivery2\x90\x04\n" +
	"\bDelivery\x12k\n" +
	"\x14GetDeliveryByOrderId\x12(.delivery.v1.GetDeliveryByOrderIdRequest\x1a).delivery.v1.GetDeliveryByOrderIdResponse\x12Y\n" +
	"\x0eListDeliveries\x12\".delivery.v1.ListDeliveriesRequest\x1a#.delivery.v1.ListDeliveriesResponse\x12Y\n" +
	"\x0eCreateDelivery\x12\".delivery.v1.CreateDeliveryRequest\x1a#.delivery.v1.CreateDeliveryResponse\x12k\n" +
	"\x14UpdateDeliveryStatus\x12(.delivery.v1.UpdateDeliveryStatusRequest\x1a).delivery.v1.UpdateDeliveryStatusResponse\x12t\n" +
	"\x17UpdateDeliveryByOrderId\x12+.delivery.v1.UpdateDeliveryByOrderIdRequest\x1a,.delivery.v1.UpdateDeliveryByOrderIdResponseB0Z.microservices/rpc/proto/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_service_proto_rawDescOnce sync.Once
	file_delivery_service_proto_rawDescData []byte
)

func file_delivery_service_proto_rawDescGZIP() []byte {
	file_delivery_service_proto_rawDescOnce.Do(func() {
		file_delivery_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_service_proto_rawDesc), len(file_delivery_service_proto_rawDesc)))
	})
	return file_delivery_service_proto_rawDescData
}

var file_delivery_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_delivery_service_proto_goTypes = []any{
	(*DeliveryDetail)(nil),                  // 0: delivery.v1.DeliveryDetail
	(*GetDeliveryByOrderIdRequest)(nil),     // 1: delivery.v1.GetDeliveryByOrderIdRequest
	(*GetDeliveryByOrderIdResponse)(nil),    // 2: delivery.v1.GetDeliveryByOrderIdResponse
	(*ListDeliveriesRequest)(nil),           // 3: delivery.v1.ListDeliveriesRequest
	(*ListDeliveriesResponse)(nil),          // 4: delivery.v1.ListDeliveriesResponse
	(*CreateDeliveryRequest)(nil),           // 5: delivery.v1.CreateDeliveryRequest
	(*CreateDeliveryResponse)(nil),          // 6: delivery.v1.CreateDeliveryResponse
	(*UpdateDeliveryStatusRequest)(nil),     // 7: delivery.v1.UpdateDeliveryStatusRequest
	(*UpdateDeliveryStatusResponse)(nil),    // 8: delivery.v1.UpdateDeliveryStatusResponse
	(*UpdateDeliveryByOrderIdRequest)(nil),  // 9: delivery.v1.UpdateDeliveryByOrderIdRequest
	(*UpdateDeliveryByOrderIdResponse)(nil), // 10: delivery.v1.UpdateDeliveryByOrderIdResponse
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_delivery_service_proto_depIdxs = []int32{
	11, // 0: delivery.v1.DeliveryDetail.dispatch_time:type_name -> google.protobuf.Timestamp
	11, // 1: delivery.v1.DeliveryDetail.pickup_time:type_name -> google.protobuf.Timestamp
	11, // 2: delivery.v1.DeliveryDetail.expected_arrival_time:type_name -> google.protobuf.Timestamp
	11, // 3: delivery.v1.DeliveryDetail.delivered_time:type_name -> google.protobuf.Timestamp
	11, // 4: delivery.v1.DeliveryDetail.create_time:type_name -> google.protobuf.Timestamp
	11, // 5: delivery.v1.DeliveryDetail.update_time:type_name -> google.protobuf.Timestamp
	0,  // 6: delivery.v1.GetDeliveryByOrderIdResponse.delivery:type_name -> delivery.v1.DeliveryDetail
	0,  // 7: delivery.v1.ListDeliveriesResponse.items:type_name -> delivery.v1.DeliveryDetail
	0,  // 8: delivery.v1.CreateDeliveryResponse.delivery:type_name -> delivery.v1.DeliveryDetail
	0,  // 9: delivery.v1.UpdateDeliveryStatusResponse.delivery:type_name -> delivery.v1.DeliveryDetail
	0,  // 10: delivery.v1.UpdateDeliveryByOrderIdResponse.delivery:type_name -> delivery.v1.DeliveryDetail
	1,  // 11: delivery.v1.Delivery.GetDeliveryByOrderId:input_type -> delivery.v1.GetDeliveryByOrderIdRequest
	3,  // 12: delivery.v1.Delivery.ListDeliveries:input_type -> delivery.v1.ListDeliveriesRequest
	5,  // 13: delivery.v1.Delivery.CreateDelivery:input_type -> delivery.v1.CreateDeliveryRequest
	7,  // 14: delivery.v1.Delivery.UpdateDeliveryStatus:input_type -> delivery.v1.UpdateDeliveryStatusRequest
	9,  // 15: delivery.v1.Delivery.UpdateDeliveryByOrderId:input_type -> delivery.v1.UpdateDeliveryByOrderIdRequest
	2,  // 16: delivery.v1.Delivery.GetDeliveryByOrderId:output_type -> delivery.v1.GetDeliveryByOrderIdResponse
	4,  // 17: delivery.v1.Delivery.ListDeliveries:output_type -> delivery.v1.ListDeliveriesResponse
	6,  // 18: delivery.v1.Delivery.CreateDelivery:output_type -> delivery.v1.CreateDeliveryResponse
	8,  // 19: delivery.v1.Delivery.UpdateDeliveryStatus:output_type -> delivery.v1.UpdateDeliveryStatusResponse
	10, // 20: delivery.v1.Delivery.UpdateDeliveryByOrderId:output_type -> delivery.v1.UpdateDeliveryByOrderIdResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_delivery_service_proto_init() }
func file_delivery_service_proto_init() {
	if File_delivery_service_proto != nil {
		return
	}
	file_delivery_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_service_proto_rawDesc), len(file_delivery_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_service_proto_goTypes,
		DependencyIndexes: file_delivery_service_proto_depIdxs,
		MessageInfos:      file_delivery_service_proto_msgTypes,
	}.Build()
	File_delivery_service_proto = out.File
	file_delivery_service_proto_goTypes = nil
	file_delivery_service_proto_depIdxs = nil
}
