// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: delivery_service.proto

package deliveryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Delivery_GetDeliveryByOrderId_FullMethodName    = "/delivery.v1.Delivery/GetDeliveryByOrderId"
	Delivery_ListDeliveries_FullMethodName          = "/delivery.v1.Delivery/ListDeliveries"
	Delivery_CreateDelivery_FullMethodName          = "/delivery.v1.Delivery/CreateDelivery"
	Delivery_UpdateDeliveryStatus_FullMethodName    = "/delivery.v1.Delivery/UpdateDeliveryStatus"
	Delivery_UpdateDeliveryByOrderId_FullMethodName = "/delivery.v1.Delivery/UpdateDeliveryByOrderId"
)

// DeliveryClient is the client API for Delivery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryClient interface {
	// GetDeliveryByOrderIdResponse 包含全表信息
	GetDeliveryByOrderId(ctx context.Context, in *GetDeliveryByOrderIdRequest, opts ...grpc.CallOption) (*GetDeliveryByOrderIdResponse, error)
	ListDeliveries(ctx context.Context, in *ListDeliveriesRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error)
	CreateDelivery(ctx context.Context, in *CreateDeliveryRequest, opts ...grpc.CallOption) (*CreateDeliveryResponse, error)
	UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*UpdateDeliveryStatusResponse, error)
	UpdateDeliveryByOrderId(ctx context.Context, in *UpdateDeliveryByOrderIdRequest, opts ...grpc.CallOption) (*UpdateDeliveryByOrderIdResponse, error)
}

type deliveryClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryClient(cc grpc.ClientConnInterface) DeliveryClient {
	return &deliveryClient{cc}
}

func (c *deliveryClient) GetDeliveryByOrderId(ctx context.Context, in *GetDeliveryByOrderIdRequest, opts ...grpc.CallOption) (*GetDeliveryByOrderIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryByOrderIdResponse)
	err := c.cc.Invoke(ctx, Delivery_GetDeliveryByOrderId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryClient) ListDeliveries(ctx context.Context, in *ListDeliveriesRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveriesResponse)
	err := c.cc.Invoke(ctx, Delivery_ListDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryClient) CreateDelivery(ctx context.Context, in *CreateDeliveryRequest, opts ...grpc.CallOption) (*CreateDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeliveryResponse)
	err := c.cc.Invoke(ctx, Delivery_CreateDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryClient) UpdateDeliveryStatus(ctx context.Context, in *UpdateDeliveryStatusRequest, opts ...grpc.CallOption) (*UpdateDeliveryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeliveryStatusResponse)
	err := c.cc.Invoke(ctx, Delivery_UpdateDeliveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryClient) UpdateDeliveryByOrderId(ctx context.Context, in *UpdateDeliveryByOrderIdRequest, opts ...grpc.CallOption) (*UpdateDeliveryByOrderIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeliveryByOrderIdResponse)
	err := c.cc.Invoke(ctx, Delivery_UpdateDeliveryByOrderId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServer is the server API for Delivery service.
// All implementations must embed UnimplementedDeliveryServer
// for forward compatibility.
type DeliveryServer interface {
	// GetDeliveryByOrderIdResponse 包含全表信息
	GetDeliveryByOrderId(context.Context, *GetDeliveryByOrderIdRequest) (*GetDeliveryByOrderIdResponse, error)
	ListDeliveries(context.Context, *ListDeliveriesRequest) (*ListDeliveriesResponse, error)
	CreateDelivery(context.Context, *CreateDeliveryRequest) (*CreateDeliveryResponse, error)
	UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*UpdateDeliveryStatusResponse, error)
	UpdateDeliveryByOrderId(context.Context, *UpdateDeliveryByOrderIdRequest) (*UpdateDeliveryByOrderIdResponse, error)
	mustEmbedUnimplementedDeliveryServer()
}

// UnimplementedDeliveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServer struct{}

func (UnimplementedDeliveryServer) GetDeliveryByOrderId(context.Context, *GetDeliveryByOrderIdRequest) (*GetDeliveryByOrderIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryByOrderId not implemented")
}
func (UnimplementedDeliveryServer) ListDeliveries(context.Context, *ListDeliveriesRequest) (*ListDeliveriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeliveries not implemented")
}
func (UnimplementedDeliveryServer) CreateDelivery(context.Context, *CreateDeliveryRequest) (*CreateDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDelivery not implemented")
}
func (UnimplementedDeliveryServer) UpdateDeliveryStatus(context.Context, *UpdateDeliveryStatusRequest) (*UpdateDeliveryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeliveryStatus not implemented")
}
func (UnimplementedDeliveryServer) UpdateDeliveryByOrderId(context.Context, *UpdateDeliveryByOrderIdRequest) (*UpdateDeliveryByOrderIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeliveryByOrderId not implemented")
}
func (UnimplementedDeliveryServer) mustEmbedUnimplementedDeliveryServer() {}
func (UnimplementedDeliveryServer) testEmbeddedByValue()                  {}

// UnsafeDeliveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServer will
// result in compilation errors.
type UnsafeDeliveryServer interface {
	mustEmbedUnimplementedDeliveryServer()
}

func RegisterDeliveryServer(s grpc.ServiceRegistrar, srv DeliveryServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Delivery_ServiceDesc, srv)
}

func _Delivery_GetDeliveryByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryByOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServer).GetDeliveryByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delivery_GetDeliveryByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServer).GetDeliveryByOrderId(ctx, req.(*GetDeliveryByOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delivery_ListDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServer).ListDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delivery_ListDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServer).ListDeliveries(ctx, req.(*ListDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delivery_CreateDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServer).CreateDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delivery_CreateDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServer).CreateDelivery(ctx, req.(*CreateDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delivery_UpdateDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServer).UpdateDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delivery_UpdateDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServer).UpdateDeliveryStatus(ctx, req.(*UpdateDeliveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delivery_UpdateDeliveryByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryByOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServer).UpdateDeliveryByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delivery_UpdateDeliveryByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServer).UpdateDeliveryByOrderId(ctx, req.(*UpdateDeliveryByOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Delivery_ServiceDesc is the grpc.ServiceDesc for Delivery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Delivery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.v1.Delivery",
	HandlerType: (*DeliveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeliveryByOrderId",
			Handler:    _Delivery_GetDeliveryByOrderId_Handler,
		},
		{
			MethodName: "ListDeliveries",
			Handler:    _Delivery_ListDeliveries_Handler,
		},
		{
			MethodName: "CreateDelivery",
			Handler:    _Delivery_CreateDelivery_Handler,
		},
		{
			MethodName: "UpdateDeliveryStatus",
			Handler:    _Delivery_UpdateDeliveryStatus_Handler,
		},
		{
			MethodName: "UpdateDeliveryByOrderId",
			Handler:    _Delivery_UpdateDeliveryByOrderId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery_service.proto",
}
