// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: order_service.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number              string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Status              int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId              uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddressBookId       uint64                 `protobuf:"varint,5,opt,name=address_book_id,json=addressBookId,proto3" json:"address_book_id,omitempty"`
	OrderTime           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	CheckoutTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=checkout_time,json=checkoutTime,proto3" json:"checkout_time,omitempty"`
	PayMethod           int32                  `protobuf:"varint,8,opt,name=pay_method,json=payMethod,proto3" json:"pay_method,omitempty"`
	PayStatus           int32                  `protobuf:"varint,9,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`
	Amount              float64                `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark              string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	Phone               string                 `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	Address             string                 `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	UserName            string                 `protobuf:"bytes,14,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Consignee           string                 `protobuf:"bytes,15,opt,name=consignee,proto3" json:"consignee,omitempty"`
	CancelReason        string                 `protobuf:"bytes,16,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	RejectionReason     string                 `protobuf:"bytes,17,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	CancelTime          *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=cancel_time,json=cancelTime,proto3" json:"cancel_time,omitempty"`
	EstimatedDeliveryAt *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=estimated_delivery_at,json=estimatedDeliveryAt,proto3" json:"estimated_delivery_at,omitempty"`
	DeliveryStatus      int32                  `protobuf:"varint,20,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"`
	DeliveryTime        *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
	PackAmount          int32                  `protobuf:"varint,22,opt,name=pack_amount,json=packAmount,proto3" json:"pack_amount,omitempty"`
	TablewareNumber     int32                  `protobuf:"varint,23,opt,name=tableware_number,json=tablewareNumber,proto3" json:"tableware_number,omitempty"`
	TablewareStatus     int32                  `protobuf:"varint,24,opt,name=tableware_status,json=tablewareStatus,proto3" json:"tableware_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *OrderDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderDetail) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *OrderDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderDetail) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderDetail) GetAddressBookId() uint64 {
	if x != nil {
		return x.AddressBookId
	}
	return 0
}

func (x *OrderDetail) GetOrderTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderTime
	}
	return nil
}

func (x *OrderDetail) GetCheckoutTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckoutTime
	}
	return nil
}

func (x *OrderDetail) GetPayMethod() int32 {
	if x != nil {
		return x.PayMethod
	}
	return 0
}

func (x *OrderDetail) GetPayStatus() int32 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *OrderDetail) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderDetail) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrderDetail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderDetail) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *OrderDetail) GetConsignee() string {
	if x != nil {
		return x.Consignee
	}
	return ""
}

func (x *OrderDetail) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *OrderDetail) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *OrderDetail) GetCancelTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelTime
	}
	return nil
}

func (x *OrderDetail) GetEstimatedDeliveryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDeliveryAt
	}
	return nil
}

func (x *OrderDetail) GetDeliveryStatus() int32 {
	if x != nil {
		return x.DeliveryStatus
	}
	return 0
}

func (x *OrderDetail) GetDeliveryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTime
	}
	return nil
}

func (x *OrderDetail) GetPackAmount() int32 {
	if x != nil {
		return x.PackAmount
	}
	return 0
}

func (x *OrderDetail) GetTablewareNumber() int32 {
	if x != nil {
		return x.TablewareNumber
	}
	return 0
}

func (x *OrderDetail) GetTablewareStatus() int32 {
	if x != nil {
		return x.TablewareStatus
	}
	return 0
}

type GetOrderByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdRequest) Reset() {
	*x = GetOrderByIdRequest{}
	mi := &file_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdRequest) ProtoMessage() {}

func (x *GetOrderByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIdRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderDetail           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdResponse) Reset() {
	*x = GetOrderByIdResponse{}
	mi := &file_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdResponse) ProtoMessage() {}

func (x *GetOrderByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIdResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderByIdResponse) GetOrder() *OrderDetail {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        *int32                 `protobuf:"varint,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderDetail         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersResponse) GetItems() []*OrderDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_order_service_proto protoreflect.FileDescriptor

const file_order_service_proto_rawDesc = "" +
	"\n" +
	"\x13order_service.proto\x12\border.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\a\n" +
	"\vOrderDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12&\n" +
	"\x0faddress_book_id\x18\x05 \x01(\x04R\raddressBookId\x129\n" +
	"\n" +
	"order_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\torderTime\x12?\n" +
	"\rcheckout_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcheckoutTime\x12\x1d\n" +
	"\n" +
	"pay_method\x18\b \x01(\x05R\tpayMethod\x12\x1d\n" +
	"\n" +
	"pay_status\x18\t \x01(\x05R\tpayStatus\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x01R\x06amount\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\x12\x14\n" +
	"\x05phone\x18\f \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\r \x01(\tR\aaddress\x12\x1b\n" +
	"\tuser_name\x18\x0e \x01(\tR\buserName\x12\x1c\n" +
	"\tconsignee\x18\x0f \x01(\tR\tconsignee\x12#\n" +
	"\rcancel_reason\x18\x10 \x01(\tR\fcancelReason\x12)\n" +
	"\x10rejection_reason\x18\x11 \x01(\tR\x0frejectionReason\x12;\n" +
	"\vcancel_time\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"cancelTime\x12N\n" +
	"\x15estimated_delivery_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\x13estimatedDeliveryAt\x12'\n" +
	"\x0fdelivery_status\x18\x14 \x01(\x05R\x0edeliveryStatus\x12?\n" +
	"\rdelivery_time\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\fdeliveryTime\x12\x1f\n" +
	"\vpack_amount\x18\x16 \x01(\x05R\n" +
	"packAmount\x12)\n" +
	"\x10tableware_number\x18\x17 \x01(\x05R\x0ftablewareNumber\x12)\n" +
	"\x10tableware_status\x18\x18 \x01(\x05R\x0ftablewareStatus\"%\n" +
	"\x13GetOrderByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"C\n" +
	"\x14GetOrderByIdResponse\x12+\n" +
	"\x05order\x18\x01 \x01(\v2\x15.order.v1.OrderDetailR\x05order\"\x85\x01\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB\t\n" +
	"\a_status\"W\n" +
	"\x12ListOrdersResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.order.v1.OrderDetailR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x9f\x01\n" +
	"\x05Order\x12M\n" +
	"\fGetOrderById\x12\x1d.order.v1.GetOrderByIdRequest\x1a\x1e.order.v1.GetOrderByIdResponse\x12G\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponseB*Z(microservices/rpc/proto/order/v1;orderv1b\x06proto3"

var (
	file_order_service_proto_rawDescOnce sync.Once
	file_order_service_proto_rawDescData []byte
)

func file_order_service_proto_rawDescGZIP() []byte {
	file_order_service_proto_rawDescOnce.Do(func() {
		file_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)))
	})
	return file_order_service_proto_rawDescData
}

var file_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_order_service_proto_goTypes = []any{
	(*OrderDetail)(nil),           // 0: order.v1.OrderDetail
	(*GetOrderByIdRequest)(nil),   // 1: order.v1.GetOrderByIdRequest
	(*GetOrderByIdResponse)(nil),  // 2: order.v1.GetOrderByIdResponse
	(*ListOrdersRequest)(nil),     // 3: order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),    // 4: order.v1.ListOrdersResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_order_service_proto_depIdxs = []int32{
	5, // 0: order.v1.OrderDetail.order_time:type_name -> google.protobuf.Timestamp
	5, // 1: order.v1.OrderDetail.checkout_time:type_name -> google.protobuf.Timestamp
	5, // 2: order.v1.OrderDetail.cancel_time:type_name -> google.protobuf.Timestamp
	5, // 3: order.v1.OrderDetail.estimated_delivery_at:type_name -> google.protobuf.Timestamp
	5, // 4: order.v1.OrderDetail.delivery_time:type_name -> google.protobuf.Timestamp
	0, // 5: order.v1.GetOrderByIdResponse.order:type_name -> order.v1.OrderDetail
	0, // 6: order.v1.ListOrdersResponse.items:type_name -> order.v1.OrderDetail
	1, // 7: order.v1.Order.GetOrderById:input_type -> order.v1.GetOrderByIdRequest
	3, // 8: order.v1.Order.ListOrders:input_type -> order.v1.ListOrdersRequest
	2, // 9: order.v1.Order.GetOrderById:output_type -> order.v1.GetOrderByIdResponse
	4, // 10: order.v1.Order.ListOrders:output_type -> order.v1.ListOrdersResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_order_service_proto_init() }
func file_order_service_proto_init() {
	if File_order_service_proto != nil {
		return
	}
	file_order_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_proto_goTypes,
		DependencyIndexes: file_order_service_proto_depIdxs,
		MessageInfos:      file_order_service_proto_msgTypes,
	}.Build()
	File_order_service_proto = out.File
	file_order_service_proto_goTypes = nil
	file_order_service_proto_depIdxs = nil
}
