// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: goods_service.proto

package goodsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGoodByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodByIdRequest) Reset() {
	*x = GetGoodByIdRequest{}
	mi := &file_goods_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodByIdRequest) ProtoMessage() {}

func (x *GetGoodByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodByIdRequest.ProtoReflect.Descriptor instead.
func (*GetGoodByIdRequest) Descriptor() ([]byte, []int) {
	return file_goods_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetGoodByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGoodByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DishId        int64                  `protobuf:"varint,3,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CreateUser    int64                  `protobuf:"varint,10,opt,name=create_user,json=createUser,proto3" json:"create_user,omitempty"`
	UpdateUser    int64                  `protobuf:"varint,11,opt,name=update_user,json=updateUser,proto3" json:"update_user,omitempty"`
	Flavors       []*DishFlavor          `protobuf:"bytes,12,rep,name=flavors,proto3" json:"flavors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodByIdResponse) Reset() {
	*x = GetGoodByIdResponse{}
	mi := &file_goods_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodByIdResponse) ProtoMessage() {}

func (x *GetGoodByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodByIdResponse.ProtoReflect.Descriptor instead.
func (*GetGoodByIdResponse) Descriptor() ([]byte, []int) {
	return file_goods_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoodByIdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetGoodByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGoodByIdResponse) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *GetGoodByIdResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetGoodByIdResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetGoodByIdResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetGoodByIdResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetGoodByIdResponse) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GetGoodByIdResponse) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *GetGoodByIdResponse) GetCreateUser() int64 {
	if x != nil {
		return x.CreateUser
	}
	return 0
}

func (x *GetGoodByIdResponse) GetUpdateUser() int64 {
	if x != nil {
		return x.UpdateUser
	}
	return 0
}

func (x *GetGoodByIdResponse) GetFlavors() []*DishFlavor {
	if x != nil {
		return x.Flavors
	}
	return nil
}

type DishFlavor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DishId        int64                  `protobuf:"varint,2,opt,name=dish_id,json=dishId,proto3" json:"dish_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishFlavor) Reset() {
	*x = DishFlavor{}
	mi := &file_goods_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishFlavor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishFlavor) ProtoMessage() {}

func (x *DishFlavor) ProtoReflect() protoreflect.Message {
	mi := &file_goods_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishFlavor.ProtoReflect.Descriptor instead.
func (*DishFlavor) Descriptor() ([]byte, []int) {
	return file_goods_service_proto_rawDescGZIP(), []int{2}
}

func (x *DishFlavor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DishFlavor) GetDishId() int64 {
	if x != nil {
		return x.DishId
	}
	return 0
}

func (x *DishFlavor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DishFlavor) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_goods_service_proto protoreflect.FileDescriptor

const file_goods_service_proto_rawDesc = "" +
	"\n" +
	"\x13goods_service.proto\x12\bgoods.v1\"$\n" +
	"\x12GetGoodByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xec\x02\n" +
	"\x13GetGoodByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\adish_id\x18\x03 \x01(\x03R\x06dishId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\x03R\n" +
	"updateTime\x12\x1f\n" +
	"\vcreate_user\x18\n" +
	" \x01(\x03R\n" +
	"createUser\x12\x1f\n" +
	"\vupdate_user\x18\v \x01(\x03R\n" +
	"updateUser\x12.\n" +
	"\aflavors\x18\f \x03(\v2\x14.goods.v1.DishFlavorR\aflavors\"_\n" +
	"\n" +
	"DishFlavor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\adish_id\x18\x02 \x01(\x03R\x06dishId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value2S\n" +
	"\x05Goods\x12J\n" +
	"\vGetGoodById\x12\x1c.goods.v1.GetGoodByIdRequest\x1a\x1d.goods.v1.GetGoodByIdResponseB*Z(microservices/rpc/proto/goods/v1;goodsv1b\x06proto3"

var (
	file_goods_service_proto_rawDescOnce sync.Once
	file_goods_service_proto_rawDescData []byte
)

func file_goods_service_proto_rawDescGZIP() []byte {
	file_goods_service_proto_rawDescOnce.Do(func() {
		file_goods_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_service_proto_rawDesc), len(file_goods_service_proto_rawDesc)))
	})
	return file_goods_service_proto_rawDescData
}

var file_goods_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_goods_service_proto_goTypes = []any{
	(*GetGoodByIdRequest)(nil),  // 0: goods.v1.GetGoodByIdRequest
	(*GetGoodByIdResponse)(nil), // 1: goods.v1.GetGoodByIdResponse
	(*DishFlavor)(nil),          // 2: goods.v1.DishFlavor
}
var file_goods_service_proto_depIdxs = []int32{
	2, // 0: goods.v1.GetGoodByIdResponse.flavors:type_name -> goods.v1.DishFlavor
	0, // 1: goods.v1.Goods.GetGoodById:input_type -> goods.v1.GetGoodByIdRequest
	1, // 2: goods.v1.Goods.GetGoodById:output_type -> goods.v1.GetGoodByIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_goods_service_proto_init() }
func file_goods_service_proto_init() {
	if File_goods_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_service_proto_rawDesc), len(file_goods_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_service_proto_goTypes,
		DependencyIndexes: file_goods_service_proto_depIdxs,
		MessageInfos:      file_goods_service_proto_msgTypes,
	}.Build()
	File_goods_service_proto = out.File
	file_goods_service_proto_goTypes = nil
	file_goods_service_proto_depIdxs = nil
}
